export const GENERAL_TOAST = "GENERAL_TOAST";
export const GENERAL_TOAST_SUCCESSFUL = "GENERAL_TOAST_SUCCESSFUL";
export const GENERAL_TOAST_ERROR = "GENERAL_TOAST_ERROR";

export const ERROR_CHECKER = "ERROR_CHECKER";
