export const FETCH_WALLET = "FETCH_WALLET";
export const FETCH_WALLET_SUCCESSFUL = "FETCH_WALLET_SUCCESSFUL";
export const FETCH_WALLET_ERROR = "FETCH_WALLET_ERROR";

export const FETCH_WALLET_BALANCE = "FETCH_WALLET_BALANCE";
export const FETCH_WALLET_BALANCE_SUCCESSFUL = "FETCH_WALLET_BALANCE_SUCCESSFUL";
export const FETCH_WALLET_BALANCE_ERROR = "FETCH_WALLET_BALANCE_ERROR";