export const LOAD_MERCHANT = "LOAD_MERCHANT";
export const LOAD_MERCHANT_SUCCESSFUL = "LOAD_MERCHANT_SUCCESSFUL";
export const LOAD_MERCHANT_ERROR = "LOAD_MERCHANT_ERROR";

export const FETCH_MERCHANT = "FETCH_MERCHANT";
export const FETCH_MERCHANT_SUCCESSFUL = "FETCH_MERCHANT_SUCCESSFUL";
export const FETCH_MERCHANT_ERROR = "FETCH_MERCHANT_ERROR";

export const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
export const UPDATE_MERCHANT_SUCCESSFUL = 'UPDATE_MERCHANT_SUCCESSFULLY';
export const UPDATE_MERCHANT_FAILED = 'FAILED';