export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTIONS_SUCCESSFUL = "FETCH_TRANSACTIONS_SUCCESSFUL";
export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";

export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const FETCH_TRANSACTION_SUCCESSFUL = "FETCH_TRANSACTION_SUCCESSFUL";
export const FETCH_TRANSACTION_ERROR = "FETCH_TRANSACTION_ERROR";

export const FETCH_TRANSACTION_ADDRESS = "FETCH_TRANSACTION_ADDRESS";
export const FETCH_TRANSACTION_ADDRESS_SUCCESSFUL = "FETCH_TRANSACTION_ADDRESS_SUCCESSFUL";
export const FETCH_TRANSACTION_ADDRESS_ERROR = "FETCH_TRANSACTION_ADDRESS_ERROR";

export const FETCH_ORPHAN_TRANSACTION = "FETCH_ORPHAN_TRANSACTION";
export const FETCH_ORPHAN_TRANSACTION_SUCCESSFUL = "FETCH_ORPHAN_TRANSACTION_SUCCESSFUL";
export const FETCH_ORPHAN_TRANSACTION_ERROR = "FETCH_ORPHAN_TRANSACTION_ERROR";

export const FETCH_ORPHAN_LOG = "FETCH_ORPHAN_LOG";
export const FETCH_ORPHAN_LOG_SUCCESSFUL = "FETCH_ORPHAN_LOG_SUCCESSFUL";
export const FETCH_ORPHAN_LOG_ERROR = "FETCH_ORPHAN_LOG_ERROR";

export const FETCH_INCOMING_TRANSACTION = "FETCH_INCOMING_TRANSACTION";
export const FETCH_INCOMING_TRANSACTION_SUCCESSFUL = "FETCH_INCOMING_TRANSACTION_SUCCESSFUL";
export const FETCH_INCOMING_TRANSACTION_ERROR = "FETCH_INCOMING_TRANSACTION_ERROR";

export const FETCH_OUTGOING_TRANSACTION = "FETCH_OUTGOING_TRANSACTION";
export const FETCH_OUTGOING_TRANSACTION_SUCCESSFUL = "FETCH_OUTGOING_TRANSACTION_SUCCESSFUL";
export const FETCH_OUTGOING_TRANSACTION_ERROR = "FETCH_OUTGOING_TRANSACTION_ERROR";
